FROM alpine:edge
ENV TAG="tag"
RUN apk update
RUN apk add go git make musl-dev musl musl-utils #python3
RUN adduser -h /home/reflect/ -D reflect reflect
RUN chown -R reflect:reflect /home/reflect
WORKDIR /home/reflect
COPY . /home/reflect
USER reflect
RUN go get -u github.com/eyedeekay/sam-forwarder/
CMD go build -o http-headers http-headers.go && ./http-headers -tag $TAG
