FROM eyedeekay/eephttpd
VOLUME /opt/eephttpd/
COPY css/styles.css /opt/eephttpd/www/css/styles.css
COPY index.html /opt/eephttpd/www/index.html
COPY favicon.ico /opt/eephttpd/www/favicon.ico
COPY include/fingerprint2.js /opt/eephttpd/www/include/fingerprint2.js
COPY /etc/eephttpd.conf /etc/eephttpd/eephttpd.conf
USER root
RUN chown -R eephttpd /opt/eephttpd/
USER eephttpd
CMD eephttpd -f /etc/eephttpd/eephttpd.conf -n fingerprintwebsite -s /opt/eephttpd/ -sh=sam-host -sp=7656 -r
